export const environment = {
  firebase: {
    apiKey: 'AIzaSyBZV4wrZH-EA4KFzjYrTh_fvsaAmIQg2BA',
    authDomain: 'awesomeonline-shop.firebaseapp.com',
    databaseURL: 'https://awesomeonline-shop.firebaseio.com',
    projectId: 'awesomeonline-shop',
    storageBucket: 'awesomeonline-shop.appspot.com',
    messagingSenderId: '820160978862',
    appId: '1:820160978862:web:74cc038e270205597cf23f',
    measurementId: 'G-MBDLTX2K8P',
    locationId: 'us-central',
  },
  production: true,
  firebaseConfig: {
    apiKey: 'AIzaSyBZV4wrZH-EA4KFzjYrTh_fvsaAmIQg2BA',
    authDomain: 'awesomeonline-shop.firebaseapp.com',
    databaseURL: 'https://awesomeonline-shop.firebaseio.com',
    projectId: 'awesomeonline-shop',
    storageBucket: 'awesomeonline-shop.appspot.com',
    messagingSenderId: '820160978862',
    appId: '1:820160978862:web:74cc038e270205597cf23f',
    measurementId: 'G-MBDLTX2K8P',
  },
  pageTitle: '',
};
